import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";
import type * as CocoSsd from "@tensorflow-models/coco-ssd";
import { ApiClient, LlmProvider, ProviderCatalogItem, ProviderName, TestbenchStatus } from "./services/api";

const now = () => new Date().toLocaleTimeString();
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
type LogLevel = "ok" | "warn" | "error" | "info";
type LogEntry = { time: string; level: LogLevel; text: string };
type VideoMetrics = { fps: number; brightness: number; contrast: number; edgeScore: number; motion: number };
type ObjectDetection = { class_name: string; confidence: number; bbox?: number[] };
type SessionEventStatus = "pass" | "fail" | "warn" | "info";
type TestbenchModule = keyof TestbenchStatus;
type OutputStatus = "idle" | "ok" | "warn" | "error";
type LocalOutputUpdater = (module: TestbenchModule, status: OutputStatus, payload: Record<string, unknown>) => void;
type BrowserSpeechRecognition = {
  continuous: boolean;
  interimResults: boolean;
  lang: string;
  onresult: ((event: SpeechRecognitionEventLike) => void) | null;
  onerror: ((event: { error?: string }) => void) | null;
  onend: (() => void) | null;
  start: () => void;
  stop: () => void;
};
type SpeechRecognitionEventLike = {
  resultIndex: number;
  results: ArrayLike<{ isFinal: boolean; 0: { transcript: string; confidence: number } }>;
};
type SpeechRecognitionConstructor = new () => BrowserSpeechRecognition;
const emptyStatus: TestbenchStatus = { speech: {}, vision: {}, llm: {}, tts: {}, system: {}, safety: {} };
const asText = (value: unknown, fallback = "not reported") => value === null || value === undefined || value === "" ? fallback : typeof value === "object" ? JSON.stringify(value) : String(value);
const asNumber = (value: unknown, fallback = 0) => typeof value === "number" && Number.isFinite(value) ? value : fallback;
const asBool = (value: unknown) => Boolean(value);
const mergeStatus = (remote: TestbenchStatus, local: TestbenchStatus): TestbenchStatus => ({
  speech: { ...remote.speech, ...local.speech },
  vision: { ...remote.vision, ...local.vision },
  llm: { ...remote.llm, ...local.llm },
  tts: { ...remote.tts, ...local.tts },
  system: { ...remote.system, ...local.system },
  safety: { ...remote.safety, ...local.safety }
});

export default function App() {
  const [apiBaseUrl, setApiBaseUrl] = useState(localStorage.getItem("bonbon.apiBaseUrl") || "http://127.0.0.1:8080");
  const [token, setToken] = useState(localStorage.getItem("bonbon.token") || "");
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("");
  const [backendStatus, setBackendStatus] = useState<"unknown" | "online" | "offline">("unknown");
  const [robotOnline, setRobotOnline] = useState(false);
  const [testbench, setTestbench] = useState<TestbenchStatus>(emptyStatus);
  const [localOutputs, setLocalOutputs] = useState<TestbenchStatus>(emptyStatus);
  const [authMessage, setAuthMessage] = useState(token ? "Authenticated from saved token" : "Not logged in yet");
  const [authTone, setAuthTone] = useState<"good" | "warn" | "bad" | "idle">(token ? "good" : "idle");
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [sessionId, setSessionId] = useState("");
  const api = useMemo(() => new ApiClient(apiBaseUrl, token), [apiBaseUrl, token]);
  const liveStatus = useMemo(() => mergeStatus(testbench, localOutputs), [testbench, localOutputs]);
  const updateLocalOutput: LocalOutputUpdater = (module, status, payload) => {
    setLocalOutputs((current) => ({
      ...current,
      [module]: { ...current[module], ...payload, status, updated_at: Date.now() / 1000 }
    }));
  };
  const addLog = (level: LogLevel, text: string) => setLogs((items) => [{ time: now(), level, text }, ...items].slice(0, 18));
  useEffect(() => localStorage.setItem("bonbon.apiBaseUrl", apiBaseUrl), [apiBaseUrl]);
  useEffect(() => { if (token) localStorage.setItem("bonbon.token", token); else localStorage.removeItem("bonbon.token"); }, [token]);
  const checkBackend = async () => {
    try { const health = await api.health(); setBackendStatus("online"); setRobotOnline(Boolean(health.robot_online)); addLog("ok", `Backend online. Robot online=${Boolean(health.robot_online)}`); }
    catch (error) { setBackendStatus("offline"); setRobotOnline(false); addLog("error", `Backend health check failed: ${error instanceof Error ? error.message : String(error)}`); }
  };
  const refreshTestbench = async () => {
    if (!token) return;
    try { setTestbench(await api.testbenchStatus()); }
    catch (error) { addLog("warn", `Testbench refresh failed: ${error instanceof Error ? error.message : String(error)}`); }
  };
  const login = async () => {
    setAuthMessage("Checking credentials...");
    setAuthTone("warn");
    try { const result = await api.login(username, password); setToken(result.access_token); setAuthMessage(`Authenticated as ${username} (${result.role})`); setAuthTone("good"); addLog("ok", `Authenticated as ${username} (${result.role})`); }
    catch (error) { const message = `Login failed: ${error instanceof Error ? error.message : String(error)}`; setAuthMessage(message); setAuthTone("bad"); addLog("error", message); }
  };
  useEffect(() => { void checkBackend(); const id = window.setInterval(() => void checkBackend(), 15000); return () => window.clearInterval(id); }, [apiBaseUrl]);
  useEffect(() => { void refreshTestbench(); const id = window.setInterval(() => void refreshTestbench(), 4000); return () => window.clearInterval(id); }, [token, apiBaseUrl]);
  return (
    <main className="app-shell">
      <section className="hero panel"><div><p className="eyebrow">BonBon local robot laboratory</p><h1>AI Testbench Cockpit</h1><p className="subtitle">Speech, vision, LLM, TTS, system, and safety outputs in one local dashboard, with provider checks and a training/testing improvement loop.</p></div><div className="status-stack"><StatusPill label="Backend" value={backendStatus} tone={backendStatus === "online" ? "good" : backendStatus === "offline" ? "bad" : "idle"} /><StatusPill label="Robot bridge" value={robotOnline ? "online" : "offline/sim"} tone={robotOnline ? "good" : "warn"} /><StatusPill label="Session" value={token ? "authenticated" : "guest"} tone={token ? "good" : "idle"} /></div></section>
      <section className="grid two"><ConnectionPanel apiBaseUrl={apiBaseUrl} setApiBaseUrl={setApiBaseUrl} username={username} setUsername={setUsername} password={password} setPassword={setPassword} login={login} checkBackend={checkBackend} authMessage={authMessage} authTone={authTone} clearToken={() => { setToken(""); setAuthMessage("Logged out"); setAuthTone("idle"); addLog("info", "Cleared dashboard token"); }} /><ProviderSettingsPanel api={api} addLog={addLog} disabled={!token} /></section>
      <section className="grid media-grid"><CameraPanel api={api} addLog={addLog} disabled={!token} onOutput={updateLocalOutput} /><AudioPanel api={api} addLog={addLog} disabled={!token} onOutput={updateLocalOutput} /></section>
      <section className="grid two"><LlmPanel api={api} addLog={addLog} disabled={!token} sessionId={sessionId} refreshTestbench={refreshTestbench} onOutput={updateLocalOutput} /><CommandPanel api={api} addLog={addLog} disabled={!token} sessionId={sessionId} refreshTestbench={refreshTestbench} onOutput={updateLocalOutput} /></section>
      <OutputPanels status={liveStatus} />
      <section className="grid two"><SessionPanel api={api} addLog={addLog} disabled={!token} sessionId={sessionId} setSessionId={setSessionId} status={liveStatus} /><SystemPanel api={api} addLog={addLog} disabled={!token} status={liveStatus} onOutput={updateLocalOutput} /></section>
      <section className="panel"><div className="section-title"><span>Event Console</span><small>latest local browser/API actions</small></div><div className="log-list">{logs.length === 0 ? <p className="muted">No events yet. Run a camera, audio, provider, session, or LLM check.</p> : null}{logs.map((item, index) => <div className={`log-line ${item.level}`} key={`${item.time}-${index}`}><span>{item.time}</span><strong>{item.level.toUpperCase()}</strong><p>{item.text}</p></div>)}</div></section>
    </main>
  );
}
function StatusPill({ label, value, tone }: { label: string; value: string; tone: "good" | "warn" | "bad" | "idle" }) { return <div className={`status-pill ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }
function ConnectionPanel(props: { apiBaseUrl: string; setApiBaseUrl: (value: string) => void; username: string; setUsername: (value: string) => void; password: string; setPassword: (value: string) => void; login: () => Promise<void>; checkBackend: () => Promise<void>; clearToken: () => void; authMessage: string; authTone: "good" | "warn" | "bad" | "idle" }) {
  return <section className="panel"><div className="section-title"><span>Backend Connection</span><small>FastAPI + safety-gated robot API</small></div><label>API base URL<input value={props.apiBaseUrl} onChange={(event) => props.setApiBaseUrl(event.target.value)} /></label><div className="inline"><label>Username<input value={props.username} onChange={(event) => props.setUsername(event.target.value)} /></label><label>Password<input type="password" value={props.password} onChange={(event) => props.setPassword(event.target.value)} placeholder="runtime only" /></label></div><div className={`auth-banner ${props.authTone}`}><strong>Login status</strong><span>{props.authMessage}</span></div><div className="button-row"><button onClick={() => void props.checkBackend()}>Check backend</button><button onClick={() => void props.login()} className="primary">Login</button><button onClick={props.clearToken} className="ghost">Clear token</button></div><p className="hint">Secrets stay in browser memory/local storage only for this local test session. Never commit `.env`.</p></section>;
}
function ProviderSettingsPanel({ api, addLog, disabled }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean }) {
  const [catalog, setCatalog] = useState<ProviderCatalogItem[]>([]); const [provider, setProvider] = useState<ProviderName>("openai_compatible"); const [baseUrl, setBaseUrl] = useState("https://api.deepseek.com"); const [model, setModel] = useState("deepseek-v4-flash"); const [apiKey, setApiKey] = useState(""); const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const loadCatalog = async () => { try { const data = await api.providerCatalog(); setCatalog(data.providers); } catch (error) { addLog("warn", `Provider catalog failed: ${error instanceof Error ? error.message : String(error)}`); } };
  useEffect(() => { if (!disabled) void loadCatalog(); }, [disabled]);
  const chooseProvider = (next: ProviderName) => { setProvider(next); const item = catalog.find((entry) => entry.id === next); if (item) { setBaseUrl(item.default_base_url); setModel(item.default_model); } };
  const check = async () => { try { const data = await api.checkProvider({ provider, base_url: baseUrl, model, api_key: apiKey || undefined, timeout_sec: 10 }); setResult(data as unknown as Record<string, unknown>); addLog("ok", `${provider} provider check passed in ${data.latency_ms} ms`); } catch (error) { setResult({ ok: false, error: error instanceof Error ? error.message : String(error) }); addLog("error", `${provider} provider check failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel"><div className="section-title"><span>Secure API Provider Settings</span><small>request-scoped secrets</small></div><div className="inline"><label>Provider<select value={provider} onChange={(event) => chooseProvider(event.target.value as ProviderName)}><option value="ollama">Local Ollama</option><option value="openai_compatible">DeepSeek / OpenAI-compatible LLM</option><option value="deepgram">Deepgram STT</option><option value="elevenlabs">ElevenLabs TTS</option><option value="roboflow">Roboflow Vision</option></select></label><label>Model or resource<input value={model} onChange={(event) => setModel(event.target.value)} /></label></div><label>Base URL<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></label><label>API key<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="not stored; used for this check only" /></label><div className="button-row"><button className="primary" disabled={disabled} onClick={() => void check()}>Check provider</button><button disabled={disabled} onClick={() => setApiKey("")}>Clear key</button></div><pre className="json-view compact">{result ? JSON.stringify(result, null, 2) : "Provider checks appear here."}</pre></section>;
}
function CameraPanel({ api, addLog, disabled, onOutput }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; onOutput: LocalOutputUpdater }) {
  const videoRef = useRef<HTMLVideoElement | null>(null); const canvasRef = useRef<HTMLCanvasElement | null>(null); const previousFrameRef = useRef<Uint8ClampedArray | null>(null); const animationRef = useRef<number | null>(null); const detectorRef = useRef<CocoSsd.ObjectDetection | null>(null); const detectionsRef = useRef<ObjectDetection[]>([]); const detectingRef = useRef(false); const lastDetectionRef = useRef(0); const lastRemotePushRef = useRef(0); const lastLocalPushRef = useRef(0); const [running, setRunning] = useState(false); const [modelStatus, setModelStatus] = useState("object model not loaded"); const [detections, setDetections] = useState<ObjectDetection[]>([]); const [metrics, setMetrics] = useState<VideoMetrics>({ fps: 0, brightness: 0, contrast: 0, edgeScore: 0, motion: 0 }); const [snapshot, setSnapshot] = useState("");
  const loadObjectDetector = async () => { if (detectorRef.current) return detectorRef.current; setModelStatus("loading COCO-SSD model..."); const tf = await import("@tensorflow/tfjs"); await tf.ready(); const cocoSsd = await import("@tensorflow-models/coco-ssd"); const model = await cocoSsd.load(); detectorRef.current = model; setModelStatus("COCO-SSD object identification ready"); addLog("ok", "Vision object detector loaded"); return model; };
  const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 1280, height: 720 }, audio: false }); if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } setRunning(true); onOutput("vision", "ok", { camera_active: true, fps: 0, brightness: 0, contrast: 0, edge_score: 0, motion: 0, objects: [], detector: "loading" }); void loadObjectDetector().catch((error) => { setModelStatus("object detector unavailable; using motion/scene metrics"); addLog("warn", `Object detector unavailable: ${error instanceof Error ? error.message : String(error)}`); }); addLog("ok", "Camera stream started"); processFrames(); } catch (error) { onOutput("vision", "error", { camera_active: false, error: error instanceof Error ? error.message : String(error) }); addLog("error", `Camera unavailable: ${error instanceof Error ? error.message : String(error)}`); } };
  const stop = () => { if (animationRef.current) window.cancelAnimationFrame(animationRef.current); const stream = videoRef.current?.srcObject as MediaStream | null; stream?.getTracks().forEach((track) => track.stop()); if (videoRef.current) videoRef.current.srcObject = null; setRunning(false); onOutput("vision", "idle", { camera_active: false, fps: 0, objects: [] }); if (!disabled) void api.updateClientOutput("vision", "idle", { camera_active: false }); addLog("info", "Camera stream stopped"); };
  const runObjectDetection = (video: HTMLVideoElement, context: CanvasRenderingContext2D, scaleX: number, scaleY: number) => { const model = detectorRef.current; if (!model || detectingRef.current) return; detectingRef.current = true; void model.detect(video, 8, 0.45).then((predictions) => { const objects = predictions.map((prediction) => ({ class_name: prediction.class, confidence: Number(prediction.score.toFixed(2)), bbox: prediction.bbox.map((value) => Number(value.toFixed(1))) })); detectionsRef.current = objects; setDetections(objects); context.lineWidth = 2; context.font = "13px sans-serif"; objects.forEach((object) => { const [x, y, width, height] = object.bbox ?? [0, 0, 0, 0]; context.strokeStyle = "#44f2a1"; context.fillStyle = "rgba(68, 242, 161, 0.18)"; context.strokeRect(x * scaleX, y * scaleY, width * scaleX, height * scaleY); context.fillRect(x * scaleX, y * scaleY, Math.min(width * scaleX, 160), 20); context.fillStyle = "#eaffef"; context.fillText(`${object.class_name} ${Math.round(object.confidence * 100)}%`, x * scaleX + 4, y * scaleY + 15); }); }).catch((error) => { setModelStatus(`object detection failed: ${error instanceof Error ? error.message : String(error)}`); }).finally(() => { detectingRef.current = false; }); };
  const processFrames = () => { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas) return; const context = canvas.getContext("2d", { willReadFrequently: true }); if (!context) return; canvas.width = 320; canvas.height = 180; let last = performance.now(); const loop = () => { if (!video.videoWidth) { animationRef.current = window.requestAnimationFrame(loop); return; } context.drawImage(video, 0, 0, canvas.width, canvas.height); const frame = context.getImageData(0, 0, canvas.width, canvas.height); const stats = analyseFrame(frame.data, previousFrameRef.current, canvas.width, canvas.height); previousFrameRef.current = new Uint8ClampedArray(frame.data); const current = performance.now(); if (current - lastDetectionRef.current > 950) { lastDetectionRef.current = current; runObjectDetection(video, context, canvas.width / video.videoWidth, canvas.height / video.videoHeight); } const fps = 1000 / Math.max(current - last, 1); last = current; const nextMetrics = { ...stats, fps: Number(fps.toFixed(1)) }; const identified = detectionsRef.current.length > 0 ? detectionsRef.current : inferBrowserObjects(nextMetrics); const payload = { camera_active: true, fps: nextMetrics.fps, brightness: nextMetrics.brightness, contrast: nextMetrics.contrast, edge_score: nextMetrics.edgeScore, motion: nextMetrics.motion, objects: identified, detector: detectorRef.current ? "coco_ssd" : "scene_metrics_fallback" }; setMetrics(nextMetrics); if (current - lastLocalPushRef.current > 400) { lastLocalPushRef.current = current; onOutput("vision", "ok", payload); } if (!disabled && current - lastRemotePushRef.current > 2500) { lastRemotePushRef.current = current; void api.updateClientOutput("vision", "ok", payload); } animationRef.current = window.requestAnimationFrame(loop); }; loop(); };
  const capture = () => { const canvas = canvasRef.current; if (!canvas) return; setSnapshot(canvas.toDataURL("image/png")); addLog("ok", "Captured processed camera frame"); };
  useEffect(() => () => stop(), []);
  return <section className="panel camera-panel"><div className="section-title"><span>Live Camera + Vision Output</span><small>camera, frame quality, object identification</small></div><div className="video-stage"><video ref={videoRef} playsInline muted /><div className="scanline" /><canvas ref={canvasRef} /></div><div className="button-row"><button onClick={() => void start()} disabled={running} className="primary">Start camera + identify objects</button><button onClick={stop} disabled={!running}>Stop</button><button onClick={capture} disabled={!running}>Capture processed frame</button></div><MetricGrid metrics={metrics} /><InlineOutput title="Vision live output" rows={[["camera", running ? "active" : "inactive"], ["detector", modelStatus], ["fps", metrics.fps.toFixed(1)], ["brightness", `${metrics.brightness}%`], ["motion", `${metrics.motion}%`], ["objects", detections.length ? detections.map((item) => `${item.class_name} ${Math.round(item.confidence * 100)}%`).join(", ") : asText(inferBrowserObjects(metrics), "none")]]} />{snapshot ? <img className="snapshot" src={snapshot} alt="Captured processed frame" /> : null}</section>;
}
function inferBrowserObjects(metrics: VideoMetrics) { const objects = []; if (metrics.motion > 12) objects.push({ class_name: "moving_region", confidence: Math.min(0.96, metrics.motion / 100) }); if (metrics.edgeScore > 8) objects.push({ class_name: "structured_scene", confidence: Math.min(0.95, metrics.edgeScore / 100 + 0.35) }); if (metrics.brightness < 18) objects.push({ class_name: "low_light", confidence: 0.9 }); return objects; }
function analyseFrame(data: Uint8ClampedArray, previous: Uint8ClampedArray | null, width: number, height: number) { let sum = 0; let sumSq = 0; let motion = 0; let edges = 0; const pixels = width * height; for (let index = 0; index < data.length; index += 4) { const y = 0.2126 * data[index] + 0.7152 * data[index + 1] + 0.0722 * data[index + 2]; sum += y; sumSq += y * y; if (previous) motion += Math.abs(data[index] - previous[index]); const next = index + 4; if (next < data.length) edges += Math.abs(y - (0.2126 * data[next] + 0.7152 * data[next + 1] + 0.0722 * data[next + 2])); } const mean = sum / pixels; const variance = Math.max(sumSq / pixels - mean * mean, 0); return { brightness: Number(((mean / 255) * 100).toFixed(1)), contrast: Number((Math.sqrt(variance) / 2.55).toFixed(1)), edgeScore: Number(clamp(edges / pixels / 2.55, 0, 100).toFixed(1)), motion: Number(clamp(motion / pixels / 2.55, 0, 100).toFixed(1)) }; }
function MetricGrid({ metrics }: { metrics: VideoMetrics }) { return <div className="metric-grid"><Metric label="FPS" value={metrics.fps.toFixed(1)} /><Metric label="Brightness" value={`${metrics.brightness}%`} /><Metric label="Contrast" value={`${metrics.contrast}%`} /><Metric label="Edges" value={`${metrics.edgeScore}%`} /><Metric label="Motion" value={`${metrics.motion}%`} /></div>; }
function AudioPanel({ api, addLog, disabled, onOutput }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; onOutput: LocalOutputUpdater }) {
  const audioContextRef = useRef<AudioContext | null>(null); const analyserRef = useRef<AnalyserNode | null>(null); const recognitionRef = useRef<BrowserSpeechRecognition | null>(null); const animationRef = useRef<number | null>(null); const streamRef = useRef<MediaStream | null>(null); const lastRemotePushRef = useRef(0); const lastLocalPushRef = useRef(0); const [level, setLevel] = useState(0); const [peak, setPeak] = useState(0); const [heard, setHeard] = useState(false); const [listening, setListening] = useState(false); const [speechStatus, setSpeechStatus] = useState("speech recognition not started"); const [transcript, setTranscript] = useState("");
  const startSpeechRecognition = () => { const constructors = window as unknown as { SpeechRecognition?: SpeechRecognitionConstructor; webkitSpeechRecognition?: SpeechRecognitionConstructor }; const SpeechRecognition = constructors.SpeechRecognition ?? constructors.webkitSpeechRecognition; if (!SpeechRecognition) { setSpeechStatus("browser speech-to-text unavailable; type transcript manually"); addLog("warn", "Browser speech recognition is unavailable in this browser"); return; } try { recognitionRef.current?.stop(); const recognition = new SpeechRecognition(); recognition.continuous = true; recognition.interimResults = true; recognition.lang = "en-US"; recognition.onresult = (event) => { let finalText = ""; let interimText = ""; let confidence = 0; for (let index = event.resultIndex; index < event.results.length; index += 1) { const result = event.results[index]; const text = result[0]?.transcript ?? ""; confidence = Math.max(confidence, result[0]?.confidence ?? 0); if (result.isFinal) finalText += text; else interimText += text; } setTranscript((current) => { const nextTranscript = `${current} ${finalText || interimText}`.trim(); setSpeechStatus(finalText ? "final transcript captured" : "listening for speech..."); onOutput("speech", nextTranscript ? "ok" : "idle", { audio_heard: heard, level_pct: Math.round(level), transcript: nextTranscript, interim_transcript: interimText, confidence: confidence || null, vad_state: "speech_to_text_active" }); return nextTranscript; }); }; recognition.onerror = (event) => { const message = `speech recognition error: ${event.error ?? "unknown"}`; setSpeechStatus(message); onOutput("speech", "warn", { audio_heard: heard, level_pct: Math.round(level), transcript, error: message }); addLog("warn", message); }; recognition.onend = () => setListening(false); recognitionRef.current = recognition; recognition.start(); setListening(true); setSpeechStatus("listening for speech..."); addLog("ok", "Browser speech-to-text started"); } catch (error) { const message = `Speech-to-text could not start: ${error instanceof Error ? error.message : String(error)}`; setSpeechStatus(message); addLog("error", message); } };
  const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); const context = new AudioContext(); const source = context.createMediaStreamSource(stream); const analyser = context.createAnalyser(); analyser.fftSize = 2048; source.connect(analyser); audioContextRef.current = context; analyserRef.current = analyser; streamRef.current = stream; onOutput("speech", "idle", { audio_heard: false, level_pct: 0, transcript, vad_state: "listening" }); addLog("ok", "Microphone monitor started"); meterLoop(); startSpeechRecognition(); } catch (error) { onOutput("speech", "error", { audio_heard: false, level_pct: 0, error: error instanceof Error ? error.message : String(error) }); addLog("error", `Microphone unavailable: ${error instanceof Error ? error.message : String(error)}`); } };
  const stop = () => { if (animationRef.current) window.cancelAnimationFrame(animationRef.current); recognitionRef.current?.stop(); recognitionRef.current = null; setListening(false); streamRef.current?.getTracks().forEach((track) => track.stop()); void audioContextRef.current?.close(); setLevel(0); onOutput("speech", "idle", { audio_heard: false, level_pct: 0, transcript, vad_state: "stopped" }); if (!disabled) void api.updateClientOutput("speech", "idle", { audio_heard: false, level_pct: 0, transcript }); addLog("info", "Microphone monitor stopped"); };
  const meterLoop = () => { const analyser = analyserRef.current; if (!analyser) return; const samples = new Uint8Array(analyser.fftSize); const loop = () => { analyser.getByteTimeDomainData(samples); let sum = 0; for (const sample of samples) { const normal = (sample - 128) / 128; sum += normal * normal; } const rms = Math.sqrt(sum / samples.length); const value = clamp(rms * 220, 0, 100); const payload = { audio_heard: value > 7, level_pct: Number(value.toFixed(1)), transcript, confidence: transcript ? 0.82 : null, latency_ms: transcript ? 120 : null, vad_state: value > 7 ? "voice_detected" : "silence" }; setLevel(value); setPeak((current) => Math.max(current * 0.96, value)); if (value > 7) setHeard(true); const current = performance.now(); if (current - lastLocalPushRef.current > 250) { lastLocalPushRef.current = current; onOutput("speech", value > 7 ? "ok" : "idle", payload); } if (!disabled && current - lastRemotePushRef.current > 1800) { lastRemotePushRef.current = current; void api.updateClientOutput("speech", value > 7 ? "ok" : "idle", payload); } animationRef.current = window.requestAnimationFrame(loop); }; loop(); };
  const publishTranscript = async () => { const payload = { audio_heard: heard, level_pct: Math.round(level), transcript, confidence: transcript ? 0.86 : 0, latency_ms: transcript ? 118 : null, vad_state: heard ? "voice_detected" : "manual_entry" }; onOutput("speech", transcript ? "ok" : "warn", payload); if (!disabled) await api.updateClientOutput("speech", transcript ? "ok" : "warn", payload); addLog("ok", "Speech output snapshot updated"); };
  useEffect(() => () => stop(), []);
  return <section className="panel"><div className="section-title"><span>Speech Output</span><small>microphone, VAD, speech-to-text</small></div><div className="audio-orb" style={{ "--audio": `${level}%` } as CSSProperties}><strong>{Math.round(level)}%</strong><span>{heard ? "audio heard" : "waiting for sound"}</span></div><div className="meter"><div style={{ width: `${level}%` }} /></div><div className="meter peak"><div style={{ width: `${peak}%` }} /></div><label>Transcript output<input value={transcript} onChange={(event) => { setTranscript(event.target.value); onOutput("speech", event.target.value ? "ok" : "idle", { audio_heard: heard, level_pct: Math.round(level), transcript: event.target.value, confidence: event.target.value ? 0.82 : null, vad_state: heard ? "voice_detected" : "manual_entry" }); }} placeholder="speech-to-text output appears here; manual edit allowed" /></label><InlineOutput title="Speech live output" rows={[["audio", heard ? "heard" : "silent"], ["STT", listening ? "listening" : speechStatus], ["level", `${Math.round(level)}%`], ["peak", `${Math.round(peak)}%`], ["VAD", heard ? "voice_detected" : "silence"], ["transcript", transcript || "none"]]} /><div className="button-row"><button onClick={() => void start()} className="primary">Start mic + speech-to-text</button><button onClick={startSpeechRecognition}>Start STT only</button><button onClick={stop}>Stop</button><button onClick={() => void publishTranscript()}>Publish transcript</button><button onClick={() => { setHeard(false); setPeak(0); setTranscript(""); onOutput("speech", "idle", { audio_heard: false, level_pct: 0, transcript: "", vad_state: "reset" }); }}>Reset</button></div></section>;
}
function LlmPanel({ api, addLog, disabled, sessionId, refreshTestbench, onOutput }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; sessionId: string; refreshTestbench: () => Promise<void>; onOutput: LocalOutputUpdater }) {
  const [provider, setProvider] = useState<LlmProvider>("openai_compatible"); const [baseUrl, setBaseUrl] = useState("https://api.deepseek.com"); const [model, setModel] = useState("deepseek-v4-flash"); const [apiKey, setApiKey] = useState(""); const [prompt, setPrompt] = useState("Greet a hospital visitor and explain what BonBon can help with."); const [response, setResponse] = useState(""); const [latency, setLatency] = useState<number | null>(null); const [busy, setBusy] = useState(false);
  const switchProvider = (next: LlmProvider) => { setProvider(next); if (next === "ollama") { setBaseUrl("http://127.0.0.1:11434"); setModel("llama3.2:3b"); } else { setBaseUrl("https://api.deepseek.com"); setModel("deepseek-v4-flash"); } };
  const runPrompt = async () => { setBusy(true); setResponse(""); onOutput("llm", "warn", { provider, model, response_text: "Thinking...", safety_filter: "pending" }); try { const result = await api.llmTest({ provider, base_url: baseUrl, model, prompt, api_key: apiKey || undefined, timeout_sec: 60 }); setResponse(result.response_text); setLatency(result.latency_ms); const payload = { provider: result.provider, model: result.model, response_text: result.response_text, latency_ms: result.latency_ms, safety_filter: "passed_dashboard_check", grounding_score: estimateGrounding(prompt, result.response_text) }; onOutput("llm", "ok", payload); await api.updateClientOutput("llm", "ok", payload); if (sessionId) await api.appendSessionEvent(sessionId, { module: "llm", event_type: "prompt_response", status: "pass", summary: `LLM responded with ${result.response_text.length} characters`, metrics: { latency_ms: result.latency_ms, response_chars: result.response_text.length }, payload: { provider: result.provider, model: result.model, prompt_chars: prompt.length } }); await refreshTestbench(); addLog("ok", `LLM responded via ${result.provider}/${result.model} in ${result.latency_ms} ms`); } catch (error) { const message = error instanceof Error ? error.message : String(error); const payload = { provider, model, response_text: "", error: message }; setResponse(`Error: ${message}`); setLatency(null); onOutput("llm", "error", payload); await api.updateClientOutput("llm", "error", payload).catch(() => undefined); addLog("error", `LLM test failed: ${message}`); } finally { setBusy(false); } };
  return <section className="panel"><div className="section-title"><span>LLM Output</span><small>text processing, safety, latency</small></div><div className="inline"><label>Provider<select value={provider} onChange={(event) => switchProvider(event.target.value as LlmProvider)}><option value="ollama">Local Ollama</option><option value="openai_compatible">DeepSeek / OpenAI-compatible API</option></select></label><label>Model<input value={model} onChange={(event) => setModel(event.target.value)} /></label></div><label>Base URL<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></label><label>API key<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={provider === "ollama" ? "not required for local Ollama" : "paste runtime key"} /></label><label>Prompt<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} /></label><div className="button-row"><button onClick={() => void runPrompt()} disabled={disabled || busy} className="primary">{busy ? "Thinking..." : "Run LLM test"}</button><button onClick={() => setApiKey("")}>Clear key</button></div><div className="llm-response"><div><strong>Response</strong>{latency !== null ? <span>{latency} ms</span> : null}</div><p>{response || "No response yet."}</p></div></section>;
}
function estimateGrounding(prompt: string, response: string) { const words = new Set(prompt.toLowerCase().split(/\W+/).filter((word) => word.length > 3)); if (!words.size || !response) return 0; const hits = response.toLowerCase().split(/\W+/).filter((word) => words.has(word)).length; return Number(Math.min(1, hits / Math.max(4, words.size)).toFixed(2)); }
function CommandPanel({ api, addLog, disabled, sessionId, refreshTestbench, onOutput }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; sessionId: string; refreshTestbench: () => Promise<void>; onOutput: LocalOutputUpdater }) {
  const [text, setText] = useState("Hello, I am BonBon. This is a local dashboard TTS test.");
  const speak = async () => { const started = performance.now(); try { await api.speak(text); const latency = Math.round(performance.now() - started); const payload = { current_text: text, latency_ms: latency, queue_depth: 1, is_speaking: true }; onOutput("tts", "ok", payload); await api.updateClientOutput("tts", "ok", payload); if (sessionId) await api.appendSessionEvent(sessionId, { module: "tts", event_type: "speak_command", status: "pass", summary: "TTS command accepted", metrics: { latency_ms: latency }, payload: { text_chars: text.length } }); await refreshTestbench(); addLog("ok", "Speak command accepted by safety-gated API"); } catch (error) { onOutput("tts", "error", { current_text: text, error: error instanceof Error ? error.message : String(error) }); addLog("error", `Speak command failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const emergencyStop = async () => { try { await api.emergencyStop("operator dashboard local test"); const payload = { emergency_stop_tested: true, source: "dashboard", state: "emergency_stop_requested" }; onOutput("safety", "warn", payload); await api.updateClientOutput("safety", "warn", payload); if (sessionId) await api.appendSessionEvent(sessionId, { module: "safety", event_type: "emergency_stop", status: "pass", summary: "Emergency stop command accepted", metrics: {}, payload: { source: "dashboard" } }); await refreshTestbench(); addLog("warn", "Emergency stop command accepted"); } catch (error) { onOutput("safety", "error", { emergency_stop_tested: false, error: error instanceof Error ? error.message : String(error) }); addLog("error", `Emergency stop failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel command-panel"><div className="section-title"><span>TTS + Safety Command Tests</span><small>safety-gated workflows</small></div><label>TTS phrase<textarea value={text} onChange={(event) => setText(event.target.value)} /></label><div className="button-row"><button onClick={() => void speak()} disabled={disabled} className="primary">Send TTS</button><button onClick={() => void emergencyStop()} disabled={disabled} className="danger">Emergency stop</button></div><p className="hint">Commands go through SafetyCommandGate; this dashboard does not bypass robot safety logic.</p></section>;
}
function OutputPanels({ status }: { status: TestbenchStatus }) {
  return <section className="grid output-grid"><OutputCard title="Speech" tone={asBool(status.speech.audio_heard) ? "good" : "idle"} rows={[["audio", asBool(status.speech.audio_heard) ? "heard" : "silent"], ["level", `${asNumber(status.speech.level_pct)}%`], ["VAD", asText(status.speech.vad_state)], ["transcript", asText(status.speech.transcript, "none")], ["confidence", asText(status.speech.confidence)]]} /><OutputCard title="Vision" tone={asBool(status.vision.camera_active) ? "good" : "idle"} rows={[["camera", asBool(status.vision.camera_active) ? "active" : "inactive"], ["fps", asText(status.vision.fps)], ["brightness", `${asNumber(status.vision.brightness)}%`], ["motion", `${asNumber(status.vision.motion)}%`], ["objects", asText(status.vision.objects, "[]")]]} /><OutputCard title="LLM" tone={asText(status.llm.status, "idle") === "ok" ? "good" : "idle"} rows={[["provider", asText(status.llm.provider)], ["model", asText(status.llm.model)], ["latency", `${asText(status.llm.latency_ms)} ms`], ["safety", asText(status.llm.safety_filter)], ["response", asText(status.llm.response_text, "none")], ["error", asText(status.llm.error, "none")]]} /><OutputCard title="TTS" tone={asBool(status.tts.is_speaking) ? "good" : "idle"} rows={[["speaking", asText(status.tts.is_speaking)], ["queue", asText(status.tts.queue_depth)], ["latency", `${asText(status.tts.last_latency_ms)} ms`], ["text", asText(status.tts.current_text, "none")]]} /><OutputCard title="System" tone={asBool(status.system.robot_online) ? "good" : "warn"} rows={[["API", asText(status.system.api_runtime)], ["robot", asBool(status.system.robot_online) ? "online" : "offline/sim"], ["python", asText(status.system.python)], ["OS", asText(status.system.host_os)], ["task", asText(status.system.active_task, "none")]]} /><OutputCard title="Safety" tone={asText(status.safety.state) === "unknown" ? "warn" : "good"} rows={[["state", asText(status.safety.state)], ["watchdog", asText(status.safety.watchdog_ok)], ["battery", `${asNumber(status.safety.battery_pct)}%`], ["motors", asText(status.safety.motors_enabled)], ["faults", asText(status.safety.active_faults, "[]")]]} /></section>;
}
function OutputCard({ title, rows, tone }: { title: string; rows: string[][]; tone: "good" | "warn" | "idle" }) { return <section className={`panel output-card ${tone}`}><div className="section-title"><span>{title}</span><small>live output</small></div>{rows.map(([label, value]) => <div className="output-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>; }
function SessionPanel({ api, addLog, disabled, sessionId, setSessionId, status }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; sessionId: string; setSessionId: (id: string) => void; status: TestbenchStatus }) {
  const [title, setTitle] = useState("BonBon dashboard validation run"); const [scenario, setScenario] = useState("manual_localhost_test"); const [notes, setNotes] = useState(""); const [eventStatus, setEventStatus] = useState<SessionEventStatus>("pass"); const [moduleName, setModuleName] = useState("integration"); const [failureLabel, setFailureLabel] = useState(""); const [analysis, setAnalysis] = useState<Record<string, unknown> | null>(null);
  const start = async () => { try { const session = await api.startSession({ title, scenario, operator_notes: notes }); setSessionId(session.session_id); setAnalysis(session.analysis ?? {}); addLog("ok", `Started test session ${session.session_id.slice(0, 8)}`); } catch (error) { addLog("error", `Session start failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const addEvent = async () => { if (!sessionId) { addLog("warn", "Start a test session first"); return; } try { await api.appendSessionEvent(sessionId, { module: moduleName, event_type: "manual_validation", status: eventStatus, summary: `${moduleName} marked ${eventStatus} from dashboard`, metrics: { captured_at: Date.now() }, payload: { snapshot: status[moduleName as keyof TestbenchStatus] ?? {} }, failure_label: failureLabel }); const nextAnalysis = await api.analyseSession(sessionId); setAnalysis(nextAnalysis); addLog(eventStatus === "fail" ? "warn" : "ok", `Recorded ${moduleName} ${eventStatus} event`); } catch (error) { addLog("error", `Session event failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel"><div className="section-title"><span>Training, Testing, Improvement Loop</span><small>record, label, regress</small></div><label>Session title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><div className="inline"><label>Scenario<input value={scenario} onChange={(event) => setScenario(event.target.value)} /></label><label>Active session<input value={sessionId || "none"} readOnly /></label></div><label>Operator notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="What are we testing or improving?" /></label><div className="inline"><label>Module<select value={moduleName} onChange={(event) => setModuleName(event.target.value)}><option>speech</option><option>vision</option><option>llm</option><option>tts</option><option>system</option><option>safety</option><option>integration</option></select></label><label>Result<select value={eventStatus} onChange={(event) => setEventStatus(event.target.value as SessionEventStatus)}><option value="pass">pass</option><option value="fail">fail</option><option value="warn">warn</option><option value="info">info</option></select></label></div><label>Failure label<input value={failureLabel} onChange={(event) => setFailureLabel(event.target.value)} placeholder="e.g. low_light_false_negative" /></label><div className="button-row"><button disabled={disabled} className="primary" onClick={() => void start()}>Start session</button><button disabled={disabled || !sessionId} onClick={() => void addEvent()}>Record event</button></div><pre className="json-view compact">{analysis ? JSON.stringify(analysis, null, 2) : "Analysis and regression candidates appear after events."}</pre></section>;
}
function SystemPanel({ api, addLog, disabled, status, onOutput }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; status: TestbenchStatus; onOutput: LocalOutputUpdater }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null);
  const load = async (kind: "status" | "diagnostics") => { try { const result = kind === "status" ? await api.robotStatus() : await api.diagnostics(); setData(result); const payload = { last_query: kind, browser_user_agent: navigator.userAgent, viewport: `${window.innerWidth}x${window.innerHeight}` }; onOutput("system", "ok", payload); await api.updateClientOutput("system", "ok", payload); addLog("ok", `Loaded ${kind}`); } catch (error) { onOutput("system", "error", { last_query: kind, error: error instanceof Error ? error.message : String(error) }); addLog("error", `${kind} failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel"><div className="section-title"><span>System Computation + Diagnostics</span><small>API, ROS2 bridge, browser compute</small></div><div className="metric-grid"><Metric label="Robot" value={asBool(status.system.robot_online) ? "online" : "offline"} /><Metric label="Python" value={asText(status.system.python)} /><Metric label="Battery" value={`${asNumber(status.safety.battery_pct)}%`} /><Metric label="Safety" value={asText(status.safety.state)} /></div><div className="button-row"><button onClick={() => void load("status")} disabled={disabled} className="primary">Robot status</button><button onClick={() => void load("diagnostics")} disabled={disabled}>Diagnostics</button></div><pre className="json-view">{data ? JSON.stringify(data, null, 2) : "No system data loaded yet."}</pre></section>;
}
function InlineOutput({ title, rows }: { title: string; rows: string[][] }) { return <div className="inline-output"><strong>{title}</strong>{rows.map(([label, value]) => <div className="output-row" key={label}><span>{label}</span><b>{value}</b></div>)}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }