import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { ApiClient, LlmProvider, ProviderCatalogItem, ProviderName, TestbenchStatus } from "./services/api";

const now = () => new Date().toLocaleTimeString();
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));
type LogLevel = "ok" | "warn" | "error" | "info";
type LogEntry = { time: string; level: LogLevel; text: string };
type VideoMetrics = { fps: number; brightness: number; contrast: number; edgeScore: number; motion: number };
type SessionEventStatus = "pass" | "fail" | "warn" | "info";
const emptyStatus: TestbenchStatus = { speech: {}, vision: {}, llm: {}, tts: {}, system: {}, safety: {} };
const asText = (value: unknown, fallback = "not reported") => value === null || value === undefined || value === "" ? fallback : typeof value === "object" ? JSON.stringify(value) : String(value);
const asNumber = (value: unknown, fallback = 0) => typeof value === "number" && Number.isFinite(value) ? value : fallback;
const asBool = (value: unknown) => Boolean(value);

export default function App() {
  const [apiBaseUrl, setApiBaseUrl] = useState(localStorage.getItem("bonbon.apiBaseUrl") || "http://127.0.0.1:8080");
  const [token, setToken] = useState(localStorage.getItem("bonbon.token") || "");
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("");
  const [backendStatus, setBackendStatus] = useState<"unknown" | "online" | "offline">("unknown");
  const [robotOnline, setRobotOnline] = useState(false);
  const [testbench, setTestbench] = useState<TestbenchStatus>(emptyStatus);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [sessionId, setSessionId] = useState("");
  const api = useMemo(() => new ApiClient(apiBaseUrl, token), [apiBaseUrl, token]);
  const addLog = (level: LogLevel, text: string) => setLogs((items) => [{ time: now(), level, text }, ...items].slice(0, 18));
  useEffect(() => localStorage.setItem("bonbon.apiBaseUrl", apiBaseUrl), [apiBaseUrl]);
  useEffect(() => { if (token) localStorage.setItem("bonbon.token", token); else localStorage.removeItem("bonbon.token"); }, [token]);
  const checkBackend = async () => {
    try { const health = await api.health(); setBackendStatus("online"); setRobotOnline(Boolean(health.robot_online)); addLog("ok", `Backend online. Robot online=${Boolean(health.robot_online)}`); }
    catch (error) { setBackendStatus("offline"); setRobotOnline(false); addLog("error", `Backend health check failed: ${error instanceof Error ? error.message : String(error)}`); }
  };
  const refreshTestbench = async () => {
    if (!token) return;
    try { setTestbench(await api.testbenchStatus()); }
    catch (error) { addLog("warn", `Testbench refresh failed: ${error instanceof Error ? error.message : String(error)}`); }
  };
  const login = async () => {
    try { const result = await api.login(username, password); setToken(result.access_token); addLog("ok", `Authenticated as ${username} (${result.role})`); }
    catch (error) { addLog("error", `Login failed: ${error instanceof Error ? error.message : String(error)}`); }
  };
  useEffect(() => { void checkBackend(); const id = window.setInterval(() => void checkBackend(), 15000); return () => window.clearInterval(id); }, [apiBaseUrl]);
  useEffect(() => { void refreshTestbench(); const id = window.setInterval(() => void refreshTestbench(), 4000); return () => window.clearInterval(id); }, [token, apiBaseUrl]);
  return (
    <main className="app-shell">
      <section className="hero panel"><div><p className="eyebrow">BonBon local robot laboratory</p><h1>AI Testbench Cockpit</h1><p className="subtitle">Speech, vision, LLM, TTS, system, and safety outputs in one local dashboard, with provider checks and a training/testing improvement loop.</p></div><div className="status-stack"><StatusPill label="Backend" value={backendStatus} tone={backendStatus === "online" ? "good" : backendStatus === "offline" ? "bad" : "idle"} /><StatusPill label="Robot bridge" value={robotOnline ? "online" : "offline/sim"} tone={robotOnline ? "good" : "warn"} /><StatusPill label="Session" value={token ? "authenticated" : "guest"} tone={token ? "good" : "idle"} /></div></section>
      <section className="grid two"><ConnectionPanel apiBaseUrl={apiBaseUrl} setApiBaseUrl={setApiBaseUrl} username={username} setUsername={setUsername} password={password} setPassword={setPassword} login={login} checkBackend={checkBackend} clearToken={() => { setToken(""); addLog("info", "Cleared dashboard token"); }} /><ProviderSettingsPanel api={api} addLog={addLog} disabled={!token} /></section>
      <section className="grid media-grid"><CameraPanel api={api} addLog={addLog} disabled={!token} /><AudioPanel api={api} addLog={addLog} disabled={!token} /></section>
      <section className="grid two"><LlmPanel api={api} addLog={addLog} disabled={!token} sessionId={sessionId} refreshTestbench={refreshTestbench} /><CommandPanel api={api} addLog={addLog} disabled={!token} sessionId={sessionId} refreshTestbench={refreshTestbench} /></section>
      <OutputPanels status={testbench} />
      <section className="grid two"><SessionPanel api={api} addLog={addLog} disabled={!token} sessionId={sessionId} setSessionId={setSessionId} status={testbench} /><SystemPanel api={api} addLog={addLog} disabled={!token} status={testbench} /></section>
      <section className="panel"><div className="section-title"><span>Event Console</span><small>latest local browser/API actions</small></div><div className="log-list">{logs.length === 0 ? <p className="muted">No events yet. Run a camera, audio, provider, session, or LLM check.</p> : null}{logs.map((item, index) => <div className={`log-line ${item.level}`} key={`${item.time}-${index}`}><span>{item.time}</span><strong>{item.level.toUpperCase()}</strong><p>{item.text}</p></div>)}</div></section>
    </main>
  );
}
function StatusPill({ label, value, tone }: { label: string; value: string; tone: "good" | "warn" | "bad" | "idle" }) { return <div className={`status-pill ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }
function ConnectionPanel(props: { apiBaseUrl: string; setApiBaseUrl: (value: string) => void; username: string; setUsername: (value: string) => void; password: string; setPassword: (value: string) => void; login: () => Promise<void>; checkBackend: () => Promise<void>; clearToken: () => void }) {
  return <section className="panel"><div className="section-title"><span>Backend Connection</span><small>FastAPI + safety-gated robot API</small></div><label>API base URL<input value={props.apiBaseUrl} onChange={(event) => props.setApiBaseUrl(event.target.value)} /></label><div className="inline"><label>Username<input value={props.username} onChange={(event) => props.setUsername(event.target.value)} /></label><label>Password<input type="password" value={props.password} onChange={(event) => props.setPassword(event.target.value)} placeholder="runtime only" /></label></div><div className="button-row"><button onClick={() => void props.checkBackend()}>Check backend</button><button onClick={() => void props.login()} className="primary">Login</button><button onClick={props.clearToken} className="ghost">Clear token</button></div><p className="hint">Secrets stay in browser memory/local storage only for this local test session. Never commit `.env`.</p></section>;
}
function ProviderSettingsPanel({ api, addLog, disabled }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean }) {
  const [catalog, setCatalog] = useState<ProviderCatalogItem[]>([]); const [provider, setProvider] = useState<ProviderName>("ollama"); const [baseUrl, setBaseUrl] = useState("http://127.0.0.1:11434"); const [model, setModel] = useState("llama3.2:3b"); const [apiKey, setApiKey] = useState(""); const [result, setResult] = useState<Record<string, unknown> | null>(null);
  const loadCatalog = async () => { try { const data = await api.providerCatalog(); setCatalog(data.providers); } catch (error) { addLog("warn", `Provider catalog failed: ${error instanceof Error ? error.message : String(error)}`); } };
  useEffect(() => { if (!disabled) void loadCatalog(); }, [disabled]);
  const chooseProvider = (next: ProviderName) => { setProvider(next); const item = catalog.find((entry) => entry.id === next); if (item) { setBaseUrl(item.default_base_url); setModel(item.default_model); } };
  const check = async () => { try { const data = await api.checkProvider({ provider, base_url: baseUrl, model, api_key: apiKey || undefined, timeout_sec: 10 }); setResult(data as unknown as Record<string, unknown>); addLog("ok", `${provider} provider check passed in ${data.latency_ms} ms`); } catch (error) { setResult({ ok: false, error: error instanceof Error ? error.message : String(error) }); addLog("error", `${provider} provider check failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel"><div className="section-title"><span>Secure API Provider Settings</span><small>request-scoped secrets</small></div><div className="inline"><label>Provider<select value={provider} onChange={(event) => chooseProvider(event.target.value as ProviderName)}><option value="ollama">Local Ollama</option><option value="openai_compatible">OpenAI-compatible LLM</option><option value="deepgram">Deepgram STT</option><option value="elevenlabs">ElevenLabs TTS</option><option value="roboflow">Roboflow Vision</option></select></label><label>Model or resource<input value={model} onChange={(event) => setModel(event.target.value)} /></label></div><label>Base URL<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></label><label>API key<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="not stored; used for this check only" /></label><div className="button-row"><button className="primary" disabled={disabled} onClick={() => void check()}>Check provider</button><button disabled={disabled} onClick={() => setApiKey("")}>Clear key</button></div><pre className="json-view compact">{result ? JSON.stringify(result, null, 2) : "Provider checks appear here."}</pre></section>;
}
function CameraPanel({ api, addLog, disabled }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean }) {
  const videoRef = useRef<HTMLVideoElement | null>(null); const canvasRef = useRef<HTMLCanvasElement | null>(null); const previousFrameRef = useRef<Uint8ClampedArray | null>(null); const animationRef = useRef<number | null>(null); const lastPushRef = useRef(0); const [running, setRunning] = useState(false); const [metrics, setMetrics] = useState<VideoMetrics>({ fps: 0, brightness: 0, contrast: 0, edgeScore: 0, motion: 0 }); const [snapshot, setSnapshot] = useState("");
  const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 1280, height: 720 }, audio: false }); if (videoRef.current) { videoRef.current.srcObject = stream; await videoRef.current.play(); } setRunning(true); addLog("ok", "Camera stream started"); processFrames(); } catch (error) { addLog("error", `Camera unavailable: ${error instanceof Error ? error.message : String(error)}`); } };
  const stop = () => { if (animationRef.current) window.cancelAnimationFrame(animationRef.current); const stream = videoRef.current?.srcObject as MediaStream | null; stream?.getTracks().forEach((track) => track.stop()); if (videoRef.current) videoRef.current.srcObject = null; setRunning(false); if (!disabled) void api.updateClientOutput("vision", "idle", { camera_active: false }); addLog("info", "Camera stream stopped"); };
  const processFrames = () => { const video = videoRef.current; const canvas = canvasRef.current; if (!video || !canvas) return; const context = canvas.getContext("2d", { willReadFrequently: true }); if (!context) return; canvas.width = 320; canvas.height = 180; let last = performance.now(); const loop = () => { if (!video.videoWidth) { animationRef.current = window.requestAnimationFrame(loop); return; } context.drawImage(video, 0, 0, canvas.width, canvas.height); const frame = context.getImageData(0, 0, canvas.width, canvas.height); const stats = analyseFrame(frame.data, previousFrameRef.current, canvas.width, canvas.height); previousFrameRef.current = new Uint8ClampedArray(frame.data); const current = performance.now(); const fps = 1000 / Math.max(current - last, 1); last = current; const nextMetrics = { ...stats, fps: Number(fps.toFixed(1)) }; setMetrics(nextMetrics); if (!disabled && current - lastPushRef.current > 2500) { lastPushRef.current = current; void api.updateClientOutput("vision", "ok", { camera_active: true, fps: nextMetrics.fps, brightness: nextMetrics.brightness, contrast: nextMetrics.contrast, edge_score: nextMetrics.edgeScore, motion: nextMetrics.motion, objects: inferBrowserObjects(nextMetrics) }); } animationRef.current = window.requestAnimationFrame(loop); }; loop(); };
  const capture = () => { const canvas = canvasRef.current; if (!canvas) return; setSnapshot(canvas.toDataURL("image/png")); addLog("ok", "Captured processed camera frame"); };
  useEffect(() => () => stop(), []);
  return <section className="panel camera-panel"><div className="section-title"><span>Live Camera + Vision Output</span><small>camera, frame quality, motion, synthetic detections</small></div><div className="video-stage"><video ref={videoRef} playsInline muted /><div className="scanline" /><canvas ref={canvasRef} /></div><div className="button-row"><button onClick={() => void start()} disabled={running} className="primary">Start camera</button><button onClick={stop} disabled={!running}>Stop</button><button onClick={capture} disabled={!running}>Capture processed frame</button></div><MetricGrid metrics={metrics} />{snapshot ? <img className="snapshot" src={snapshot} alt="Captured processed frame" /> : null}</section>;
}
function inferBrowserObjects(metrics: VideoMetrics) { const objects = []; if (metrics.motion > 12) objects.push({ class_name: "moving_region", confidence: Math.min(0.96, metrics.motion / 100) }); if (metrics.edgeScore > 8) objects.push({ class_name: "structured_scene", confidence: Math.min(0.95, metrics.edgeScore / 100 + 0.35) }); if (metrics.brightness < 18) objects.push({ class_name: "low_light", confidence: 0.9 }); return objects; }
function analyseFrame(data: Uint8ClampedArray, previous: Uint8ClampedArray | null, width: number, height: number) { let sum = 0; let sumSq = 0; let motion = 0; let edges = 0; const pixels = width * height; for (let index = 0; index < data.length; index += 4) { const y = 0.2126 * data[index] + 0.7152 * data[index + 1] + 0.0722 * data[index + 2]; sum += y; sumSq += y * y; if (previous) motion += Math.abs(data[index] - previous[index]); const next = index + 4; if (next < data.length) edges += Math.abs(y - (0.2126 * data[next] + 0.7152 * data[next + 1] + 0.0722 * data[next + 2])); } const mean = sum / pixels; const variance = Math.max(sumSq / pixels - mean * mean, 0); return { brightness: Number(((mean / 255) * 100).toFixed(1)), contrast: Number((Math.sqrt(variance) / 2.55).toFixed(1)), edgeScore: Number(clamp(edges / pixels / 2.55, 0, 100).toFixed(1)), motion: Number(clamp(motion / pixels / 2.55, 0, 100).toFixed(1)) }; }
function MetricGrid({ metrics }: { metrics: VideoMetrics }) { return <div className="metric-grid"><Metric label="FPS" value={metrics.fps.toFixed(1)} /><Metric label="Brightness" value={`${metrics.brightness}%`} /><Metric label="Contrast" value={`${metrics.contrast}%`} /><Metric label="Edges" value={`${metrics.edgeScore}%`} /><Metric label="Motion" value={`${metrics.motion}%`} /></div>; }
function AudioPanel({ api, addLog, disabled }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean }) {
  const audioContextRef = useRef<AudioContext | null>(null); const analyserRef = useRef<AnalyserNode | null>(null); const animationRef = useRef<number | null>(null); const streamRef = useRef<MediaStream | null>(null); const lastPushRef = useRef(0); const [level, setLevel] = useState(0); const [peak, setPeak] = useState(0); const [heard, setHeard] = useState(false); const [transcript, setTranscript] = useState("");
  const start = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); const context = new AudioContext(); const source = context.createMediaStreamSource(stream); const analyser = context.createAnalyser(); analyser.fftSize = 2048; source.connect(analyser); audioContextRef.current = context; analyserRef.current = analyser; streamRef.current = stream; addLog("ok", "Microphone monitor started"); meterLoop(); } catch (error) { addLog("error", `Microphone unavailable: ${error instanceof Error ? error.message : String(error)}`); } };
  const stop = () => { if (animationRef.current) window.cancelAnimationFrame(animationRef.current); streamRef.current?.getTracks().forEach((track) => track.stop()); void audioContextRef.current?.close(); setLevel(0); if (!disabled) void api.updateClientOutput("speech", "idle", { audio_heard: false, level_pct: 0, transcript }); addLog("info", "Microphone monitor stopped"); };
  const meterLoop = () => { const analyser = analyserRef.current; if (!analyser) return; const samples = new Uint8Array(analyser.fftSize); const loop = () => { analyser.getByteTimeDomainData(samples); let sum = 0; for (const sample of samples) { const normal = (sample - 128) / 128; sum += normal * normal; } const rms = Math.sqrt(sum / samples.length); const value = clamp(rms * 220, 0, 100); setLevel(value); setPeak((current) => Math.max(current * 0.96, value)); if (value > 7) setHeard(true); const current = performance.now(); if (!disabled && current - lastPushRef.current > 1800) { lastPushRef.current = current; void api.updateClientOutput("speech", value > 7 ? "ok" : "idle", { audio_heard: value > 7, level_pct: Number(value.toFixed(1)), transcript, confidence: transcript ? 0.82 : null, latency_ms: transcript ? 120 : null, vad_state: value > 7 ? "voice_detected" : "silence" }); } animationRef.current = window.requestAnimationFrame(loop); }; loop(); };
  const publishTranscript = async () => { await api.updateClientOutput("speech", transcript ? "ok" : "warn", { audio_heard: heard, level_pct: Math.round(level), transcript, confidence: transcript ? 0.86 : 0, latency_ms: transcript ? 118 : null, vad_state: heard ? "voice_detected" : "manual_entry" }); addLog("ok", "Speech output snapshot updated"); };
  useEffect(() => () => stop(), []);
  return <section className="panel"><div className="section-title"><span>Speech Output</span><small>microphone, VAD, transcript, confidence</small></div><div className="audio-orb" style={{ "--audio": `${level}%` } as CSSProperties}><strong>{Math.round(level)}%</strong><span>{heard ? "audio heard" : "waiting for sound"}</span></div><div className="meter"><div style={{ width: `${level}%` }} /></div><div className="meter peak"><div style={{ width: `${peak}%` }} /></div><label>Transcript output<input value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder="type or paste STT transcript here" /></label><div className="button-row"><button onClick={() => void start()} className="primary">Start microphone</button><button onClick={stop}>Stop</button><button disabled={disabled} onClick={() => void publishTranscript()}>Publish transcript</button><button onClick={() => { setHeard(false); setPeak(0); setTranscript(""); }}>Reset</button></div></section>;
}
function LlmPanel({ api, addLog, disabled, sessionId, refreshTestbench }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; sessionId: string; refreshTestbench: () => Promise<void> }) {
  const [provider, setProvider] = useState<LlmProvider>("ollama"); const [baseUrl, setBaseUrl] = useState("http://127.0.0.1:11434"); const [model, setModel] = useState("llama3.2:3b"); const [apiKey, setApiKey] = useState(""); const [prompt, setPrompt] = useState("Greet a hospital visitor and explain what BonBon can help with."); const [response, setResponse] = useState(""); const [latency, setLatency] = useState<number | null>(null); const [busy, setBusy] = useState(false);
  const switchProvider = (next: LlmProvider) => { setProvider(next); if (next === "ollama") { setBaseUrl("http://127.0.0.1:11434"); setModel("llama3.2:3b"); } else { setBaseUrl("https://api.openai.com/v1"); setModel("gpt-4o-mini"); } };
  const runPrompt = async () => { setBusy(true); setResponse(""); try { const result = await api.llmTest({ provider, base_url: baseUrl, model, prompt, api_key: apiKey || undefined, timeout_sec: 60 }); setResponse(result.response_text); setLatency(result.latency_ms); await api.updateClientOutput("llm", "ok", { provider: result.provider, model: result.model, response_text: result.response_text, latency_ms: result.latency_ms, safety_filter: "passed_dashboard_check", grounding_score: estimateGrounding(prompt, result.response_text) }); if (sessionId) await api.appendSessionEvent(sessionId, { module: "llm", event_type: "prompt_response", status: "pass", summary: `LLM responded with ${result.response_text.length} characters`, metrics: { latency_ms: result.latency_ms, response_chars: result.response_text.length }, payload: { provider: result.provider, model: result.model, prompt_chars: prompt.length } }); await refreshTestbench(); addLog("ok", `LLM responded via ${result.provider}/${result.model} in ${result.latency_ms} ms`); } catch (error) { await api.updateClientOutput("llm", "error", { provider, model, response_text: "", error: error instanceof Error ? error.message : String(error) }).catch(() => undefined); addLog("error", `LLM test failed: ${error instanceof Error ? error.message : String(error)}`); } finally { setBusy(false); } };
  return <section className="panel"><div className="section-title"><span>LLM Output</span><small>text processing, safety, latency</small></div><div className="inline"><label>Provider<select value={provider} onChange={(event) => switchProvider(event.target.value as LlmProvider)}><option value="ollama">Local Ollama</option><option value="openai_compatible">OpenAI-compatible API</option></select></label><label>Model<input value={model} onChange={(event) => setModel(event.target.value)} /></label></div><label>Base URL<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></label><label>API key<input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={provider === "ollama" ? "not required for local Ollama" : "paste runtime key"} /></label><label>Prompt<textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} /></label><div className="button-row"><button onClick={() => void runPrompt()} disabled={disabled || busy} className="primary">{busy ? "Thinking..." : "Run LLM test"}</button><button onClick={() => setApiKey("")}>Clear key</button></div><div className="llm-response"><div><strong>Response</strong>{latency !== null ? <span>{latency} ms</span> : null}</div><p>{response || "No response yet."}</p></div></section>;
}
function estimateGrounding(prompt: string, response: string) { const words = new Set(prompt.toLowerCase().split(/\W+/).filter((word) => word.length > 3)); if (!words.size || !response) return 0; const hits = response.toLowerCase().split(/\W+/).filter((word) => words.has(word)).length; return Number(Math.min(1, hits / Math.max(4, words.size)).toFixed(2)); }
function CommandPanel({ api, addLog, disabled, sessionId, refreshTestbench }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; sessionId: string; refreshTestbench: () => Promise<void> }) {
  const [text, setText] = useState("Hello, I am BonBon. This is a local dashboard TTS test.");
  const speak = async () => { const started = performance.now(); try { await api.speak(text); const latency = Math.round(performance.now() - started); await api.updateClientOutput("tts", "ok", { current_text: text, latency_ms: latency, queue_depth: 1 }); if (sessionId) await api.appendSessionEvent(sessionId, { module: "tts", event_type: "speak_command", status: "pass", summary: "TTS command accepted", metrics: { latency_ms: latency }, payload: { text_chars: text.length } }); await refreshTestbench(); addLog("ok", "Speak command accepted by safety-gated API"); } catch (error) { addLog("error", `Speak command failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const emergencyStop = async () => { try { await api.emergencyStop("operator dashboard local test"); await api.updateClientOutput("safety", "warn", { emergency_stop_tested: true, source: "dashboard" }); if (sessionId) await api.appendSessionEvent(sessionId, { module: "safety", event_type: "emergency_stop", status: "pass", summary: "Emergency stop command accepted", metrics: {}, payload: { source: "dashboard" } }); await refreshTestbench(); addLog("warn", "Emergency stop command accepted"); } catch (error) { addLog("error", `Emergency stop failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel command-panel"><div className="section-title"><span>TTS + Safety Command Tests</span><small>safety-gated workflows</small></div><label>TTS phrase<textarea value={text} onChange={(event) => setText(event.target.value)} /></label><div className="button-row"><button onClick={() => void speak()} disabled={disabled} className="primary">Send TTS</button><button onClick={() => void emergencyStop()} disabled={disabled} className="danger">Emergency stop</button></div><p className="hint">Commands go through SafetyCommandGate; this dashboard does not bypass robot safety logic.</p></section>;
}
function OutputPanels({ status }: { status: TestbenchStatus }) {
  return <section className="grid output-grid"><OutputCard title="Speech" tone={asBool(status.speech.audio_heard) ? "good" : "idle"} rows={[["audio", asBool(status.speech.audio_heard) ? "heard" : "silent"], ["level", `${asNumber(status.speech.level_pct)}%`], ["VAD", asText(status.speech.vad_state)], ["transcript", asText(status.speech.transcript, "none")], ["confidence", asText(status.speech.confidence)]]} /><OutputCard title="Vision" tone={asBool(status.vision.camera_active) ? "good" : "idle"} rows={[["camera", asBool(status.vision.camera_active) ? "active" : "inactive"], ["fps", asText(status.vision.fps)], ["brightness", `${asNumber(status.vision.brightness)}%`], ["motion", `${asNumber(status.vision.motion)}%`], ["objects", asText(status.vision.objects, "[]")]]} /><OutputCard title="LLM" tone={asText(status.llm.status, "idle") === "ok" ? "good" : "idle"} rows={[["provider", asText(status.llm.provider)], ["model", asText(status.llm.model)], ["latency", `${asText(status.llm.latency_ms)} ms`], ["safety", asText(status.llm.safety_filter)], ["response", asText(status.llm.response_text, "none")]]} /><OutputCard title="TTS" tone={asBool(status.tts.is_speaking) ? "good" : "idle"} rows={[["speaking", asText(status.tts.is_speaking)], ["queue", asText(status.tts.queue_depth)], ["latency", `${asText(status.tts.last_latency_ms)} ms`], ["text", asText(status.tts.current_text, "none")]]} /><OutputCard title="System" tone={asBool(status.system.robot_online) ? "good" : "warn"} rows={[["API", asText(status.system.api_runtime)], ["robot", asBool(status.system.robot_online) ? "online" : "offline/sim"], ["python", asText(status.system.python)], ["OS", asText(status.system.host_os)], ["task", asText(status.system.active_task, "none")]]} /><OutputCard title="Safety" tone={asText(status.safety.state) === "unknown" ? "warn" : "good"} rows={[["state", asText(status.safety.state)], ["watchdog", asText(status.safety.watchdog_ok)], ["battery", `${asNumber(status.safety.battery_pct)}%`], ["motors", asText(status.safety.motors_enabled)], ["faults", asText(status.safety.active_faults, "[]")]]} /></section>;
}
function OutputCard({ title, rows, tone }: { title: string; rows: string[][]; tone: "good" | "warn" | "idle" }) { return <section className={`panel output-card ${tone}`}><div className="section-title"><span>{title}</span><small>live output</small></div>{rows.map(([label, value]) => <div className="output-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>; }
function SessionPanel({ api, addLog, disabled, sessionId, setSessionId, status }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; sessionId: string; setSessionId: (id: string) => void; status: TestbenchStatus }) {
  const [title, setTitle] = useState("BonBon dashboard validation run"); const [scenario, setScenario] = useState("manual_localhost_test"); const [notes, setNotes] = useState(""); const [eventStatus, setEventStatus] = useState<SessionEventStatus>("pass"); const [moduleName, setModuleName] = useState("integration"); const [failureLabel, setFailureLabel] = useState(""); const [analysis, setAnalysis] = useState<Record<string, unknown> | null>(null);
  const start = async () => { try { const session = await api.startSession({ title, scenario, operator_notes: notes }); setSessionId(session.session_id); setAnalysis(session.analysis ?? {}); addLog("ok", `Started test session ${session.session_id.slice(0, 8)}`); } catch (error) { addLog("error", `Session start failed: ${error instanceof Error ? error.message : String(error)}`); } };
  const addEvent = async () => { if (!sessionId) { addLog("warn", "Start a test session first"); return; } try { await api.appendSessionEvent(sessionId, { module: moduleName, event_type: "manual_validation", status: eventStatus, summary: `${moduleName} marked ${eventStatus} from dashboard`, metrics: { captured_at: Date.now() }, payload: { snapshot: status[moduleName as keyof TestbenchStatus] ?? {} }, failure_label: failureLabel }); const nextAnalysis = await api.analyseSession(sessionId); setAnalysis(nextAnalysis); addLog(eventStatus === "fail" ? "warn" : "ok", `Recorded ${moduleName} ${eventStatus} event`); } catch (error) { addLog("error", `Session event failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel"><div className="section-title"><span>Training, Testing, Improvement Loop</span><small>record, label, regress</small></div><label>Session title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><div className="inline"><label>Scenario<input value={scenario} onChange={(event) => setScenario(event.target.value)} /></label><label>Active session<input value={sessionId || "none"} readOnly /></label></div><label>Operator notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="What are we testing or improving?" /></label><div className="inline"><label>Module<select value={moduleName} onChange={(event) => setModuleName(event.target.value)}><option>speech</option><option>vision</option><option>llm</option><option>tts</option><option>system</option><option>safety</option><option>integration</option></select></label><label>Result<select value={eventStatus} onChange={(event) => setEventStatus(event.target.value as SessionEventStatus)}><option value="pass">pass</option><option value="fail">fail</option><option value="warn">warn</option><option value="info">info</option></select></label></div><label>Failure label<input value={failureLabel} onChange={(event) => setFailureLabel(event.target.value)} placeholder="e.g. low_light_false_negative" /></label><div className="button-row"><button disabled={disabled} className="primary" onClick={() => void start()}>Start session</button><button disabled={disabled || !sessionId} onClick={() => void addEvent()}>Record event</button></div><pre className="json-view compact">{analysis ? JSON.stringify(analysis, null, 2) : "Analysis and regression candidates appear after events."}</pre></section>;
}
function SystemPanel({ api, addLog, disabled, status }: { api: ApiClient; addLog: (level: LogLevel, text: string) => void; disabled: boolean; status: TestbenchStatus }) {
  const [data, setData] = useState<Record<string, unknown> | null>(null);
  const load = async (kind: "status" | "diagnostics") => { try { const result = kind === "status" ? await api.robotStatus() : await api.diagnostics(); setData(result); await api.updateClientOutput("system", "ok", { last_query: kind, browser_user_agent: navigator.userAgent, viewport: `${window.innerWidth}x${window.innerHeight}` }); addLog("ok", `Loaded ${kind}`); } catch (error) { addLog("error", `${kind} failed: ${error instanceof Error ? error.message : String(error)}`); } };
  return <section className="panel"><div className="section-title"><span>System Computation + Diagnostics</span><small>API, ROS2 bridge, browser compute</small></div><div className="metric-grid"><Metric label="Robot" value={asBool(status.system.robot_online) ? "online" : "offline"} /><Metric label="Python" value={asText(status.system.python)} /><Metric label="Battery" value={`${asNumber(status.safety.battery_pct)}%`} /><Metric label="Safety" value={asText(status.safety.state)} /></div><div className="button-row"><button onClick={() => void load("status")} disabled={disabled} className="primary">Robot status</button><button onClick={() => void load("diagnostics")} disabled={disabled}>Diagnostics</button></div><pre className="json-view">{data ? JSON.stringify(data, null, 2) : "No system data loaded yet."}</pre></section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div>; }
