"""
bonbon_llm.safety.authorization
================================
Command authorization layer — gates LLM-proposed behaviors against the
live SafetyState before anything reaches the actuation or navigation stack.

Architecture
------------
The LLM NEVER directly controls actuators or navigation.  It produces
BehaviorRecommendation messages which this module validates against the
current SafetyState snapshot before forwarding.

Authorization table
-------------------
  navigate_to / approach_person:
    → Requires SafetyState.navigation_permitted = True
    → Requires safety_state in {NORMAL, DOCKING} (not CAUTION/DANGER/FAULT/…)

  serve_item:
    → Requires SafetyState.actuation_permitted = True
    → Requires safety_state in {NORMAL}

  speak_* / idle / wait_for_input:
    → Always permitted (speech never requires Safety Supervisor approval)

  alert_safety:
    → Always permitted; generated by the safety system, not the LLM.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from enum import StrEnum

from bonbon_llm.config.llm_config import AuthorizationConfig

logger = logging.getLogger(__name__)


# ── SafetyState constants (mirror SafetyState.msg) ───────────────────────────

SAFETY_INITIALIZING = 0
SAFETY_NORMAL = 1
SAFETY_CAUTION = 2
SAFETY_DANGER = 3
SAFETY_DOCKING = 4
SAFETY_DEGRADED = 5
SAFETY_FAULT = 6
SAFETY_SAFE_STOP = 7

_NAVIGATION_ALLOWED_STATES = frozenset({SAFETY_NORMAL, SAFETY_DOCKING})
_ACTUATION_ALLOWED_STATES = frozenset({SAFETY_NORMAL})


# ── Result type ───────────────────────────────────────────────────────────────


class AuthStatus(StrEnum):
    GRANTED = "GRANTED"
    DENIED = "DENIED"
    DEFERRED = "DEFERRED"  # ask again when safety state improves


@dataclass
class AuthorizationResult:
    status: AuthStatus
    reason: str
    behavior_class: str
    requires_confirmation: bool = False  # True → robot must confirm with user first
    timestamp: float = 0.0

    def __post_init__(self):
        if self.timestamp == 0.0:
            self.timestamp = time.monotonic()

    @property
    def granted(self) -> bool:
        return self.status == AuthStatus.GRANTED


# ── Snapshot of safety state (passed in from ROS2 callback) ──────────────────


@dataclass
class SafetySnapshot:
    state_id: int = SAFETY_NORMAL
    state_name: str = "NORMAL"
    actuation_permitted: bool = True
    navigation_permitted: bool = True
    max_velocity_mps: float = 0.8
    requires_manual_reset: bool = False

    @classmethod
    def from_ros_msg(cls, msg) -> SafetySnapshot:
        return cls(
            state_id=int(msg.state),
            state_name=str(msg.state_name),
            actuation_permitted=bool(msg.actuation_permitted),
            navigation_permitted=bool(msg.navigation_permitted),
            max_velocity_mps=float(msg.max_velocity_mps),
            requires_manual_reset=bool(msg.requires_manual_reset),
        )

    @classmethod
    def safe_default(cls) -> SafetySnapshot:
        """Permissive default — used before first SafetyState message arrives."""
        return cls(
            state_id=SAFETY_NORMAL,
            state_name="NORMAL",
            actuation_permitted=True,
            navigation_permitted=True,
        )


# ── Authorizer ────────────────────────────────────────────────────────────────


class CommandAuthorizer:
    """
    Stateless command authorizer.  Thread-safe.

    The current SafetySnapshot is passed into each ``authorize`` call so
    there is no hidden state and the decision is reproducible.
    """

    def __init__(self, cfg: AuthorizationConfig) -> None:
        self._cfg = cfg

    def authorize(
        self,
        behavior_class: str,
        safety: SafetySnapshot,
        confidence: float = 1.0,
    ) -> AuthorizationResult:
        """
        Decide whether ``behavior_class`` may be dispatched given ``safety``.

        Returns GRANTED, DENIED, or DEFERRED.
        """
        bc = behavior_class.lower()

        # ── Speech / informational — always permitted ─────────────────────────
        if self._is_speech_only(bc):
            return AuthorizationResult(
                status=AuthStatus.GRANTED,
                reason="Speech output does not require safety authorization",
                behavior_class=behavior_class,
            )

        # ── Hard-stopped states — deny everything except speech ───────────────
        if safety.requires_manual_reset:
            return AuthorizationResult(
                status=AuthStatus.DENIED,
                reason=f"Manual reset required (state={safety.state_name}); "
                f"behavior {behavior_class!r} denied",
                behavior_class=behavior_class,
            )

        if safety.state_id == SAFETY_SAFE_STOP:
            return AuthorizationResult(
                status=AuthStatus.DENIED,
                reason="E-stop engaged; all actuation denied",
                behavior_class=behavior_class,
            )

        # ── Navigation behaviors ──────────────────────────────────────────────
        if bc in self._cfg.navigation_intent_classes:
            if not self._cfg.require_safety_normal_for_navigation:
                pass  # config override: skip state check
            elif safety.state_id not in _NAVIGATION_ALLOWED_STATES:
                return AuthorizationResult(
                    status=AuthStatus.DENIED,
                    reason=f"Navigation not permitted in state {safety.state_name!r}",
                    behavior_class=behavior_class,
                )

            if not safety.navigation_permitted:
                return AuthorizationResult(
                    status=AuthStatus.DENIED,
                    reason="SafetyState.navigation_permitted is False",
                    behavior_class=behavior_class,
                )

            return AuthorizationResult(
                status=AuthStatus.GRANTED,
                reason="Navigation permitted by SafetyState",
                behavior_class=behavior_class,
                requires_confirmation=confidence < self._cfg.authorization_timeout_sec,
            )

        # ── Actuation behaviors ───────────────────────────────────────────────
        if bc in self._cfg.actuation_intent_classes:
            if self._cfg.require_actuation_permitted and not safety.actuation_permitted:
                return AuthorizationResult(
                    status=AuthStatus.DENIED,
                    reason="SafetyState.actuation_permitted is False",
                    behavior_class=behavior_class,
                )

            if safety.state_id not in _ACTUATION_ALLOWED_STATES:
                deferred = safety.state_id in (SAFETY_CAUTION, SAFETY_DEGRADED)
                return AuthorizationResult(
                    status=AuthStatus.DEFERRED if deferred else AuthStatus.DENIED,
                    reason=f"Actuation not permitted in state {safety.state_name!r}",
                    behavior_class=behavior_class,
                )

            return AuthorizationResult(
                status=AuthStatus.GRANTED,
                reason="Actuation permitted by SafetyState",
                behavior_class=behavior_class,
            )

        # ── Default: grant anything not explicitly navigation/actuation ───────
        return AuthorizationResult(
            status=AuthStatus.GRANTED,
            reason="Behavior class granted by default",
            behavior_class=behavior_class,
        )

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def _is_speech_only(bc: str) -> bool:
        return bc.startswith("speak_") or bc in {
            "idle",
            "wait_for_input",
            "alert_safety",
            "stop_navigation",
        }
