"""ServoValidator — validates servo command targets against safe mechanical limits.

Every servo command generated by the actuation pipeline is passed through this
validator before being sent to the HAL.  Out-of-range positions are **clamped**
(not rejected) so the robot always reaches the closest safe position.  Unknown
servo IDs are treated as hard errors.

Velocity is also clamped to [MIN_VEL_DPS, MAX_VEL_DPS] to protect gearboxes
from runaway speed values.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Dict, List, Tuple

from bonbon_actuation.core.gesture_library import SERVO_LIMITS, ServoTarget

_logger = logging.getLogger(__name__)

# Velocity guard-rails (degrees per second).
MIN_VEL_DPS: float = 5.0
MAX_VEL_DPS: float = 200.0


@dataclass
class ValidationResult:
    """Result of a single validation pass over a list of servo targets."""

    valid: bool
    """``True`` when there are no *hard* errors (unknown servo IDs)."""

    clamped_targets: List[ServoTarget]
    """Targets with positions and velocities clamped to safe limits."""

    warnings: List[str] = field(default_factory=list)
    """Non-fatal issues that were automatically corrected."""

    errors: List[str] = field(default_factory=list)
    """Fatal issues that prevent any of the targets from being executed."""


class ServoValidator:
    """Validate and clamp servo commands to safe operating limits.

    Args:
        limits: Optional override for per-servo ``(min_deg, max_deg)`` limits.
                Defaults to the module-level :data:`SERVO_LIMITS` table.
    """

    def __init__(self, limits: Dict[int, Tuple[float, float]] | None = None) -> None:
        self._limits: Dict[int, Tuple[float, float]] = (
            dict(limits) if limits is not None else dict(SERVO_LIMITS)
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def validate(self, targets: List[ServoTarget]) -> ValidationResult:
        """Validate *targets* and return a :class:`ValidationResult`.

        Unknown servo IDs produce an error entry and the target is excluded
        from ``clamped_targets``.  All other targets are clamped in place.

        Args:
            targets: Iterable of :class:`ServoTarget` objects to validate.

        Returns:
            A :class:`ValidationResult` with ``valid=True`` when no unknown
            servo IDs were encountered.
        """
        clamped: List[ServoTarget] = []
        warnings: List[str] = []
        errors: List[str] = []

        for t in targets:
            if t.servo_id not in self._limits:
                msg = f"Unknown servo_id={t.servo_id}; target discarded."
                _logger.error(msg)
                errors.append(msg)
                continue  # skip — cannot safely clamp an unknown servo

            lo, hi = self._limits[t.servo_id]

            # Clamp position.
            if t.position_deg < lo or t.position_deg > hi:
                clamped_pos = max(lo, min(hi, t.position_deg))
                warnings.append(
                    f"Servo {t.servo_id}: position {t.position_deg:.1f}° clamped to "
                    f"{clamped_pos:.1f}° (limit [{lo}, {hi}])."
                )
                _logger.warning(
                    "Servo %d position %.1f° outside [%.1f, %.1f] → clamped to %.1f°",
                    t.servo_id, t.position_deg, lo, hi, clamped_pos,
                )
            else:
                clamped_pos = t.position_deg

            # Clamp velocity.
            if t.velocity_dps < MIN_VEL_DPS or t.velocity_dps > MAX_VEL_DPS:
                clamped_vel = max(MIN_VEL_DPS, min(MAX_VEL_DPS, t.velocity_dps))
                warnings.append(
                    f"Servo {t.servo_id}: velocity {t.velocity_dps:.1f} dps clamped to "
                    f"{clamped_vel:.1f} dps."
                )
                _logger.warning(
                    "Servo %d velocity %.1f dps outside [%.1f, %.1f] → clamped to %.1f",
                    t.servo_id, t.velocity_dps, MIN_VEL_DPS, MAX_VEL_DPS, clamped_vel,
                )
            else:
                clamped_vel = t.velocity_dps

            clamped.append(ServoTarget(t.servo_id, clamped_pos, clamped_vel))

        return ValidationResult(
            valid=len(errors) == 0,
            clamped_targets=clamped,
            warnings=warnings,
            errors=errors,
        )

    def add_limit(self, servo_id: int, min_deg: float, max_deg: float) -> None:
        """Register or override the limit for a servo.

        Args:
            servo_id: The servo identifier.
            min_deg: Minimum safe position (degrees).
            max_deg: Maximum safe position (degrees).
        """
        if min_deg >= max_deg:
            raise ValueError(
                f"Invalid limits for servo {servo_id}: min ({min_deg}) >= max ({max_deg})"
            )
        self._limits[servo_id] = (min_deg, max_deg)
        _logger.debug("Servo %d limits updated: [%.1f, %.1f]", servo_id, min_deg, max_deg)
