"""Project status API — test results, known issues, and deployment
readiness, generated by the project's own verification tooling rather than
fabricated. Each endpoint honestly reports "not available" when its
backing file is missing instead of inventing data.

Data sources (relative to OperatorAPIConfig.project_status_dir, default
"devops" — see that config field's own docstring for the deployment
override):
  test-results/latest.json       — written by the project's verification
                                    passes; see PHASE2_BUILD_VALIDATION_REPORT.md
  project-status/known_issues.json — hand-maintained list of confirmed,
                                    verified findings (not auto-generated;
                                    each entry traces to a specific
                                    investigation, see that file's "source"
                                    field)
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, Request

from bonbon_operator_api.auth.dependencies import require_permission
from bonbon_operator_api.models.auth_models import TokenPayload
from bonbon_operator_api.models.response_models import APIResponse

logger = logging.getLogger(__name__)

project_status_router = APIRouter(prefix="/diagnostics", tags=["project-status"])


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Failed to read project status file %s: %s", path, exc)
        return None


@project_status_router.get("/test-results", response_model=APIResponse)
async def get_test_results(
    request: Request,
    current_user: TokenPayload = Depends(require_permission("diagnostics:read")),
) -> APIResponse:
    """Return the most recent recorded test run summary, or an honest
    "not available" payload if no report has been generated."""
    status_dir: Path = request.app.state.cfg.project_status_dir
    data = _read_json(status_dir / "test-results" / "latest.json")
    if data is None:
        return APIResponse.ok(
            {
                "available": False,
                "message": "No test results report found at "
                f"{status_dir / 'test-results' / 'latest.json'}.",
            }
        )
    return APIResponse.ok({"available": True, **data})


@project_status_router.get("/known-issues", response_model=APIResponse)
async def get_known_issues(
    request: Request,
    current_user: TokenPayload = Depends(require_permission("diagnostics:read")),
) -> APIResponse:
    """Return the hand-maintained list of confirmed, verified findings
    (redundancy cleanup status, incomplete features, build blockers)."""
    status_dir: Path = request.app.state.cfg.project_status_dir
    data = _read_json(status_dir / "project-status" / "known_issues.json")
    if data is None:
        return APIResponse.ok(
            {
                "available": False,
                "message": "No known-issues report found at "
                f"{status_dir / 'project-status' / 'known_issues.json'}.",
                "issues": [],
            }
        )
    return APIResponse.ok({"available": True, **data})


@project_status_router.get("/deployment-readiness", response_model=APIResponse)
async def get_deployment_readiness(
    request: Request,
    current_user: TokenPayload = Depends(require_permission("diagnostics:read")),
) -> APIResponse:
    """Compute an overall deployment-readiness verdict from live robot
    state plus the known-issues report's blocking-issue count. This is a
    derived judgment, not a separate data source — it never claims
    readiness the underlying signals don't support."""
    aggregator = request.app.state.status_aggregator
    status = aggregator.get_status()

    status_dir: Path = request.app.state.cfg.project_status_dir
    issues_data = _read_json(status_dir / "project-status" / "known_issues.json")
    issues = issues_data.get("issues", []) if issues_data else []
    blocking_issues = [i for i in issues if i.get("blocking_deployment") is True]

    test_data = _read_json(status_dir / "test-results" / "latest.json")
    tests_known_failing = bool(test_data and test_data.get("total_failed", 0) > 0)

    reasons: list[str] = []
    if blocking_issues:
        reasons.append(f"{len(blocking_issues)} known blocking issue(s) unresolved")
    if tests_known_failing:
        reasons.append("most recent test run recorded failures")
    if status.safety.state in ("fault", "safe_stop"):
        reasons.append(f"safety state is '{status.safety.state}'")
    if not status.is_online:
        reasons.append("robot is not currently connected to the dashboard")

    ready = len(reasons) == 0
    return APIResponse.ok(
        {
            "ready": ready,
            "reasons": reasons,
            "blocking_issue_count": len(blocking_issues),
            "blocking_issues": blocking_issues,
            "robot_online": status.is_online,
            "safety_state": status.safety.state,
            "last_known_test_failures": test_data.get("total_failed") if test_data else None,
        }
    )
